[project]
name = "mnemonic-gen"
version = "0.1.0"
description = "Generate mnemonic sentences for English words"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "datasets>=3.0.2",
  "gradio>=5.4.0",
  "openai>=1.52.2",
  "pre-commit>=4.0.1",
  "python-dotenv>=1.0.1",
  "pyyaml>=6.0.2",
  "ruff",
  "tenacity>=9.0.0",
  "torch",
  "tqdm>=4.66.5",
  "transformers>=4.46.0",
  "wandb>=0.18.5",
]

[project.urls]
repository = "https://github.com/chiffonng/capstone"

[project.optional-dependencies]
plot = ["ipykernel>=6.29.5", "matplotlib>=3.9.2"]
data = ["pandas>=2.2.3", "pyarrow>=17.0.0"]
all  = ["matplotlib>=3.9.2", "pandas>=2.2.3", "pyarrow>=17.0.0"]

[tool.ruff]
src            = ["src"]
target-version = "py312"
extend-exclude = ["*__init__.py", "*.pyi"]

[tool.ruff.format]
docstring-code-format      = true # format code in docstrings
docstring-code-line-length = 88

[tool.ruff.lint]
extend-select = [
  "B",   # flake8-bugbear, bugbear checks
  "D",   # pydocstyle, all functions and classes must have docstrings
  "I",   # isort
  "PT",  # flakes8-pytest-style, pytest fixtures and style
  "PTH", # flake8-use-pathlib, use pathlib instead of os.path
]
extend-safe-fixes = [
  "ANN",  # missing type annotation
  "D",    # pydocstyle docstrings
  "DOC",  # pydoclint docstring conventions
  "F",    # pyflakes
  "I002", # missing import
  "ICN",  # import conventions
  "LOG",  # logging conventions
  "Q",    # flake8-quotes
]
extend-fixable = ["B"]
ignore = ["T201", "T203", "F401"] # print, pprint statements OK, unused imports OK
isort.case-sensitive = true
flake8-type-checking.quote-annotations = true
pydocstyle.convention = "google"
pycodestyle.max-doc-length = 88

[tool.uv]
python-downloads = "manual"         # change to "automatic" to download Python specified in .python-version
upgrade-package  = ["ruff", "tqdm"]
managed          = true
