[project]
name = "mnemonic-gen"
version = "0.2.0"
description = "Generate mnemonic sentences for English words"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "datasets", # Hugging Face datasets
  "evaluate",
  "hf-transfer>=0.1.8",
  "matplotlib>=3.9.2",
  "numpy<2.0.0",
  "peft", # HF parameter-efficient training
  "pre-commit>=4.0.1", # Pre-commit hooks
  "python-dotenv>=1.0.1", # Load environment variables
  "pyyaml>=6.0.2", # YAML config
  "ruff>=0.9.7",
  "seaborn>=0.13.2",
  "spaces>=0.31.0",
  "torch==2.4.0", # PyTorch
  "tqdm>=4.67.1", # Progress bar
  "transformers", # HF transformers
  "trl>=0.11.0", # Transformer reinforcement learning
  "wandb", # Weights and Biases for logging
]

[project.urls]
repository = "https://github.com/chiffonng/capstone"
dataset    = "https://doi.org/10.57967/hf/3750"

[project.optional-dependencies]
data = [
    "openai>=1.57.0",
    "pandas>=2.2.3",
    "pyarrow>=18.1.0",
    "tiktoken>=0.9.0",
]

[tool.ruff]
src            = ["src"]
target-version = "py310"
extend-exclude = ["*__init__.py", "*.pyi"]

[tool.ruff.format]
docstring-code-format      = true # format code in docstrings
docstring-code-line-length = 88

[tool.ruff.lint]
exclude = ["*__init__.py", "*.ipynb"] # Do not lint __init__.py and Jupyter notebooks
extend-select = [
  "B",   # flake8-bugbear, bugbear checks
  "D",   # pydocstyle, all functions and classes must have docstrings
  "I",   # isort
  "PT",  # flakes8-pytest-style, pytest fixtures and style
  "PTH", # flake8-use-pathlib, use pathlib instead of os.path
  "B",   # flake8-bugbear, bugbear checks
  "D",   # pydocstyle, all functions and classes must have docstrings
  "I",   # isort
  "PT",  # flakes8-pytest-style, pytest fixtures and style
  "PTH", # flake8-use-pathlib, use pathlib instead of os.path
]
extend-safe-fixes = [
  "ANN",  # missing type annotation
  "D",    # pydocstyle docstrings
  "DOC",  # pydoclint docstring conventions
  "F",    # pyflakes
  "I002", # missing import
  "ICN",  # import conventions
  "LOG",  # logging conventions
  "Q",    # flake8-quotes
]
extend-fixable = ["B", "D"]
ignore = ["T201", "T203", "F401"] # print, pprint statements OK, unused imports OK
isort.case-sensitive = true
flake8-type-checking.quote-annotations = true
pydocstyle.convention = "google"
pycodestyle.max-doc-length = 88

[tool.uv]
python-downloads = "manual"         # change to "automatic" to download Python specified in .python-version
upgrade-package  = ["ruff", "tqdm"]
managed          = true
