prompts:
  system: |
    You are an expert in English mnemonics. Your task is to classify each mnemonic as one of the following: shallow-encoding (1), deep-encoding (2), mixed (3), or unsure (0). Think through the reasoning for classification yourself, and respond consistently with the response format. You have to classify every mnemonic in the prompt, no more no less. If unsure, return 0. \n
    Classify the mnemonics below based on the following criteria:\n
    - Shallow (1): Focus on how the word sounds, looks, or rhymes.
    - Deep (2): Focus on semantics, morphology, etymology, context (inferred meaning, imagery), related words (synonyms, antonyms, words with same roots). Repeating the word or using a similar-sounding word is NOT deep-encoding.
    - Mixed (3): Contains both shallow and deep features.\n

    Examples:
    - olfactory: Sounds like "old factory." The old factory had a strong smell, reminding workers of its olfactory history. Classification: shallow (1), since it's based on the sound.
    - vacuous: Same Latin root "vacare" (empty) as "vacuum, vacant". His expression was as empty as a vacuum, showing no signs of thought. Classification: deep (2), since it only uses etymology and related words.
    - malevolent: From male 'ill' + volent 'wishing' (as in "benevolent"). These male species are so violent that they always have evil plans. Classification: mixed (3) since it uses etymology and antonyms (deep-encoding), and the sounds of "male" and "violent" (shallow-encoding)\n
  user: Mnemonics are seperated by a newline character. Please classify each mnemonic in the same order as they appear in the prompt.\n
model: "gpt-4o-mini"
temperature: 0.2
num_outputs: 1
batch_size: 50
